-d E:\book_chip\course_ud\RISC_V\practice_code\uart_tx_rx_3mode_led_breadboard\impl\gwsynthesis\3mode_gpio_led_uart.vg
-p GW1NR-9C-QFN88P-6
-pn GW1NR-LV9QN88PC6/I5
-cst E:\book_chip\course_ud\RISC_V\practice_code\uart_tx_rx_3mode_led_breadboard\src\rv32.cst
-cfg E:\book_chip\course_ud\RISC_V\practice_code\uart_tx_rx_3mode_led_breadboard\impl\pnr\device.cfg
-sdc E:\book_chip\course_ud\RISC_V\practice_code\uart_tx_rx_3mode_led_breadboard\src\picotiny.sdc
-bit
-tr
-ph
-timing
-cst_error
-convert_sdp32_36_to_sdp16_18
-place_option 0
-route_option 0
-clock_route_order 0
-correct_hold 1
-route_maxfan 23
-global_freq 50.000
